name: Build and publish
on:
  release:
    types:
      - published

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Log in to the google cloud container registry
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet
      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/registry/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
